# Generated by Django 5.2.17 on 2026-10-01 15:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Sede",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=100, unique=True)),
                ("ciudad", models.CharField(blank=True, max_length=100)),
                (
                    "direccion",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="dirección"
                    ),
                ),
                (
                    "telefono",
                    models.CharField(
                        blank=True, max_length=30, verbose_name="teléfono"
                    ),
                ),
                ("activa", models.BooleanField(default=True)),
            ],
            options={
                "ordering": ["nombre"],
            },
        ),
        migrations.CreateModel(
            name="PerfilSede",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "usuario",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="perfil_sede",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "sedes",
                    models.ManyToManyField(
                        blank=True, related_name="usuarios", to="sedes.sede"
                    ),
                ),
            ],
            options={
                "verbose_name": "acceso a sedes",
                "verbose_name_plural": "accesos a sedes",
            },
        ),
    ]
