# Generated by Django 5.2.17 on 2026-10-01 15:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("aulas", "0001_initial"),
        ("sedes", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Grupo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=150)),
                ("curso", models.CharField(blank=True, max_length=150)),
                (
                    "num_alumnos",
                    models.PositiveSmallIntegerField(
                        default=0, verbose_name="nº de alumnos"
                    ),
                ),
                ("requiere_ordenadores", models.BooleanField(default=False)),
                ("requiere_proyector", models.BooleanField(default=False)),
                (
                    "requiere_accesibilidad",
                    models.BooleanField(
                        default=False,
                        verbose_name="tiene alumnos con movilidad reducida",
                    ),
                ),
                (
                    "aula",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="grupos",
                        to="aulas.aula",
                    ),
                ),
                (
                    "sede",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="grupos",
                        to="sedes.sede",
                    ),
                ),
            ],
            options={
                "ordering": ["sede", "nombre"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("sede", "nombre"), name="grupo_unico_por_sede"
                    )
                ],
            },
        ),
    ]
