# Generated by Django 5.2.17 on 2026-10-01 15:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("sedes", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Aula",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=100)),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("teorica", "Teórica"),
                            ("informatica", "Informática"),
                            ("taller", "Taller"),
                            ("reuniones", "Sala de reuniones"),
                        ],
                        default="teorica",
                        max_length=20,
                    ),
                ),
                (
                    "capacidad",
                    models.PositiveSmallIntegerField(
                        help_text="Número máximo de alumnos"
                    ),
                ),
                ("proyector", models.BooleanField(default=False)),
                ("ordenadores", models.BooleanField(default=False)),
                (
                    "accesible",
                    models.BooleanField(
                        default=False, verbose_name="accesible (movilidad reducida)"
                    ),
                ),
                ("activa", models.BooleanField(default=True)),
                (
                    "restricciones",
                    models.TextField(
                        blank=True,
                        help_text="Notas libres: ruido, horarios de uso, normas…",
                    ),
                ),
                (
                    "sede",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="aulas",
                        to="sedes.sede",
                    ),
                ),
            ],
            options={
                "ordering": ["sede", "nombre"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("sede", "nombre"), name="aula_unica_por_sede"
                    )
                ],
            },
        ),
    ]
